Rebilly/rebilly-recomponents

- package.json
- packages/recomponents/package.json
Try to update version for semantic release
> fix(tools): Update package.json to work with semantic release

- packages/recomponents/src/components/r-checkbox/r-checkbox.scss
- packages/recomponents/src/components/r-dropdown/r-dropdown.scss
- packages/recomponents/src/components/r-icon/r-icon.scss
- packages/recomponents/src/components/r-input/r-input.scss
- packages/recomponents/src/components/r-radio/r-toggle.scss
- packages/recomponents/src/directives/r-tooltip.scss
- packages/recomponents/src/index.js
- packages/recomponents/src/styles/mixins.scss
- Removed prefix usage
- Checked the autoprefixer
- Added dropdown and icon button recomponents to the export
> Use autoprefixer

- packages/recomponents/README.md
Outdated example in main readme
Updated example in readme + added link to jsfiddle
> docs(readme): update example in main readme

- packages/recomponents/src/components/r-badge/r-badge.scss
- packages/recomponents/src/components/r-button/r-button.scss
- packages/recomponents/src/components/r-button/r-button.spec.js
- packages/recomponents/src/components/r-button/r-button.story.js
- packages/recomponents/src/components/r-button/r-button.vue
- packages/recomponents/src/components/r-checkbox/r-checkbox.scss
- packages/recomponents/src/components/r-dropdown/r-dropdown.scss
- packages/recomponents/src/components/r-icon-button/r-icon-button.story.js
- packages/recomponents/src/components/r-icon-button/r-icon-button.vue
- packages/recomponents/src/components/r-icon/r-icon.scss
- packages/recomponents/src/components/r-input/r-input.scss
- packages/recomponents/src/components/r-loader/r-loader.scss
- packages/recomponents/src/components/r-radio/r-toggle.scss
- packages/recomponents/src/components/r-tile/r-tile.scss
- packages/recomponents/src/directives/r-tooltip.scss
- packages/recomponents/src/styles/theme.scss
Themes file needed some style rework
- Most variables were defined
- Added component-specific variables for easy tweaking
All component variables reference the global variables. Maybe we can remove already the variables file
Also, I removed the warning button styles. I don't think we need to those for now
> Refactor components styles

- packages/recomponents/src/components/r-button/r-button.scss
- packages/recomponents/src/components/r-button/r-button.story.js
- packages/recomponents/src/components/r-button/r-button.vue
> feat(r-button): Add link option for button

- README.md
I saw this #19 and thought it was unnecessary. 
It links to the storybook which is already built automatically using AWS Amplify console.
n/a
> Link to the storybook

- packages/recomponents/src/components/r-button/r-button.md
update doc
more clear on how to import a single component
None
> docs(button): update doc

- packages/gridsome/src/components/Tabs.vue
- packages/gridsome/src/layouts/Default.vue
- packages/gridsome/src/pages/Tabs.vue
- packages/nuxt/components/Tabs.vue
- packages/nuxt/pages/index.vue
- packages/nuxt/pages/tabs.vue
- packages/recomponents/src/components/r-tabs/__snapshots__/r-tabs.spec.js.snap
- packages/recomponents/src/components/r-tabs/r-tab.vue
- packages/recomponents/src/components/r-tabs/r-tabs.md
- packages/recomponents/src/components/r-tabs/r-tabs.scss
- packages/recomponents/src/components/r-tabs/r-tabs.spec.js
- packages/recomponents/src/components/r-tabs/r-tabs.story.js
- packages/recomponents/src/components/r-tabs/r-tabs.vue
- packages/recomponents/src/index.js
- packages/recomponents/src/styles/theme.scss
> feat(tabs): create tabs component

- packages/recomponents/src/components/r-tabs/r-tabs.scss
- packages/recomponents/src/components/r-tabs/r-tabs.story.js
- packages/recomponents/src/components/r-tile/r-tile.scss
- packages/recomponents/src/directives/r-tooltip.js
- packages/recomponents/src/directives/r-tooltip.scss
- packages/recomponents/src/stories/payment-form.story.js
- packages/recomponents/src/styles/theme.scss
Hardcoded values where part of the tooltip directive
Removed values and added 2 more attributes to include those values 
I also updated the styles for `r-tabs` and updated some stories to use the right `r-tile` component
> Removed harcoded values on tooltip directive

- packages/recomponents/package.json
Cannot pass Travis build in another application
Change version of yarn is enough to fix that issue
> fix(tools): decrease yarn version

- packages/nuxt/components/Pagination.vue
- packages/nuxt/pages/index.vue
- packages/nuxt/pages/pagination.vue
- packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination.spec.js.snap
- packages/recomponents/src/components/r-pagination/r-pagination-control.scss
- packages/recomponents/src/components/r-pagination/r-pagination-control.vue
- packages/recomponents/src/components/r-pagination/r-pagination.md
- packages/recomponents/src/components/r-pagination/r-pagination.spec.js
- packages/recomponents/src/components/r-pagination/r-pagination.story.js
- packages/recomponents/src/components/r-pagination/r-pagination.vue
- packages/recomponents/src/index.js
- packages/recomponents/src/styles/theme.scss
Created `r-pagination` component
> feat(r-pagination): create pagination component

- packages/recomponents/src/components/r-modal/__snapshots__/r-modal.spec.js.snap
- packages/recomponents/src/components/r-modal/r-modal.scss
- packages/recomponents/src/components/r-modal/r-modal.vue
rename .modal to .r-modal so that no conflicts in recomm
> refactor(r-modal): rename .modal to .r-modal so that no conflicts in recomm

- packages/recomponents/package.json
As the previous keyword `refactor` can't trigger the release automatically, `fix` can. 
I'd like to release it to NPM
> fix(style): just release it as refactor can't be triggered

- packages/recomponents/src/components/r-pagination/r-pagination.vue
Chrome crashes when visiting pagination component
Infinite loop in code, fixed it
> fix(r-pagination): fix Infinite loop

- README.md
Cannot trigger release via CI
Yet another attempt before start dive into this issue
Weird issue, could waste lot of our time
> fix(release): trigger release by readme update

- packages/recomponents/src/components/r-input/r-input.spec.js
- packages/recomponents/src/components/r-input/r-input.story.js
- packages/recomponents/src/components/r-input/r-input.vue
- packages/recomponents/src/styles/theme.scss
Invalid state of input looks incorrect:
Updated styles and knobs in Storybook to test this case.
Found that we can group knobs together in storybook, we should add this everywhere to keep knobs better structured
> Fix invalid state of RInput

- packages/recomponents/src/components/r-select/__snapshots__/r-select.spec.js.snap
- packages/recomponents/src/components/r-select/r-select.scss
- packages/recomponents/src/components/r-select/r-select.spec.js
- packages/recomponents/src/components/r-select/r-select.story.js
- packages/recomponents/src/components/r-select/r-select.vue
While integrating `r-select` component, there were found some issues. 
- support custom labels and values
-
> fix(r-select): update select component, support custom label and value

- packages/recomponents/src/components/r-badge/r-badge.scss
- packages/recomponents/src/components/r-select/r-select.md
- packages/recomponents/src/components/r-select/r-select.scss
- packages/recomponents/src/components/r-select/r-select.story.js
- packages/recomponents/src/components/r-select/r-select.vue
- packages/recomponents/src/styles/theme.scss
Change styles for `r-select` component. Update docs with actual description.
> update r-select styles

- packages/recomponents/src/components/r-select/r-select.scss
- packages/recomponents/src/components/r-select/r-select.story.js
- packages/recomponents/src/styles/theme.scss
- packages/recomponents/yarn.lock
Style updates is enough to fix that issue.
> Fix empty select jumping

- packages/recomponents/src/components/r-badge/r-badge.story.js
- packages/recomponents/src/components/r-select/r-select.spec.js
- packages/recomponents/src/components/r-select/r-select.vue
Eslint locally cannot pass checks
Autofix + variable rename is enough to pass build
> Fix eslint errors

- packages/recomponents/.storybook/config.js
- packages/recomponents/package.json
- packages/recomponents/src/components/r-badge/r-badge.story.js
- packages/recomponents/src/components/r-button/r-button.spec.js
- packages/recomponents/src/components/r-button/r-button.vue
- packages/recomponents/src/components/r-checkbox/r-checkbox.spec.js
- packages/recomponents/src/components/r-checkbox/r-checkbox.vue
- packages/recomponents/src/components/r-date-input/r-date-input.spec.js
- packages/recomponents/src/components/r-modal/r-modal.spec.js
- packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination-control.spec.js.snap
- packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination.spec.js.snap
- packages/recomponents/src/components/r-pagination/r-pagination-control.spec.js
- packages/recomponents/src/components/r-pagination/r-pagination.spec.js
- packages/recomponents/src/components/r-popper/r-popper.spec.js
- packages/recomponents/src/components/r-radio/r-radio.spec.js
- packages/recomponents/src/components/r-select/__snapshots__/r-select.spec.js.snap
- packages/recomponents/src/components/r-select/r-select.spec.js
- packages/recomponents/src/components/r-select/r-select.vue
- packages/recomponents/src/index.js
- packages/recomponents/yarn.lock
There was removed usage of i18n in all components
> Remove i18n dependency

- packages/recomponents/src/components/r-select/r-select.story.js
- packages/recomponents/src/components/r-select/r-select.vue
When the prop value equals null, there are errors in console and the selector doesn't render
> fix(r-select): null value fix

- packages/recomponents/.storybook/config.js
- packages/recomponents/.storybook/manager-head.html
- packages/recomponents/.storybook/theme.js
Default theme of storybook looks too... default.
Feel free to add any suggestions.
> Add branding to storybook

- packages/recomponents/src/components/r-loader/__snapshots__/r-loader.spec.js.snap
- packages/recomponents/src/components/r-loader/r-loader.scss
- packages/recomponents/src/components/r-loader/r-loader.spec.js
- packages/recomponents/src/components/r-loader/r-loader.story.js
- packages/recomponents/src/components/r-loader/r-loader.vue
- packages/recomponents/src/components/r-modal/__snapshots__/r-modal.spec.js.snap
- packages/recomponents/src/styles/theme.scss
Fullscreen mode is unsupported.
> Update r-loader styles trying to support fullscreen mode

- packages/recomponents/src/components/r-button/r-button.scss
- packages/recomponents/src/components/r-pagination/r-pagination-control.scss
- packages/recomponents/src/components/r-popper/r-popper.scss
- packages/recomponents/src/components/r-popper/r-popper.story.js
- packages/recomponents/src/styles/theme.scss
- packages/recomponents/src/styles/typography.scss
There are some issues when tested in IE11
Not related to IE
- some of CSS vars are not defined but are used
- fix the style for the RPopper story
Bugs on IE11
- the height of pagination is not correct on IE11
- RPopper story can't be shown on IE11
> The issues on IE11

- packages/recomponents/src/components/r-loader/r-loader.scss
- packages/recomponents/src/styles/theme.scss
- packages/recomponents/yarn.lock
Full screen loader and inline loader works incorrect on same page at sam
Full screen loader has +1 z-index than inline loader
> fix(component): Allow on one page fullscreen loader with inline

- packages/recomponents/src/components/r-modal/__snapshots__/r-modal.spec.js.snap
- packages/recomponents/src/components/r-modal/r-modal.scss
- packages/recomponents/src/components/r-modal/r-modal.story.js
- packages/recomponents/src/components/r-modal/r-modal.vue
- packages/recomponents/src/components/r-popper/r-popper.scss
- packages/recomponents/src/components/r-popper/r-popper.story.js
- packages/recomponents/src/components/r-popper/r-popper.vue
- packages/recomponents/src/styles/animate.scss
- When RPopper is shown, no transition, fixed it.
- Added **duration** for RPopper transition.
- Added **duration** for RModal transition.
> fix(all): fix the transition bugs and improve transition

- packages/recomponents/src/components/r-modal/r-modal.vue
Add r-no-scroll to body only the modal opens
GWY-14656
> fix(RModal): add r-no-scroll to body only the modal opens

- packages/recomponents/src/components/r-select/r-select.md
- packages/recomponents/src/components/r-select/r-select.story.js
- packages/recomponents/src/components/r-select/r-select.vue
The `r-select` value can be validated, but we should be able to validate separately tags.
> fix(r-select): Support tag validation

- packages/recomponents/src/components/r-pagination/r-pagination.vue
RPagination can dive into infinite loop if 0 pages will be passed to it
Added check for this case
> fix(component): Fix RPagination if no pages passed

- packages/recomponents/src/components/r-popper/r-popper.scss
- packages/recomponents/src/components/r-popper/r-popper.story.js
> fix(r-popper): hide scrollbar

- packages/recomponents/package.json
Master branch was not released due to version error
> fix(master): version build fix

- packages/recomponents/.storybook/knobs.js
- packages/recomponents/src/components/r-icon/r-icon-sprites.js
> Add report match icon

- packages/recomponents/src/components/r-modal/r-modal.vue
- packages/recomponents/src/styles/helpers.scss
The wrong helper classes were being referenced.
> fix(header-actions): Fix header actions spacing

- packages/recomponents/src/components/r-modal/r-modal.vue
Fixes a minor spacing issue in the header of very thin fluid modals
> fix(header-actions): Fix minor spacing issue

- packages/recomponents/src/components/r-grid/r-grid.scss
- packages/recomponents/src/components/r-grid/r-grid.story.js
Fix the padding and left absolute positioning of frozen column
> Hotfix for r-grid

- packages/recomponents/src/components/r-input/r-input.spec.js
- packages/recomponents/src/components/r-input/r-input.story.js
- packages/recomponents/src/components/r-input/r-input.vue
* Add `$attr` to input elements to pass attributes from component to the element.
> Pass custom data attributes to input from r-input component

- packages/recomponents/src/components/r-grid/columnTypes/numeric.js
- packages/recomponents/src/components/r-grid/helpers/color-generator.js
- packages/recomponents/src/components/r-grid/r-grid.scss
- packages/recomponents/src/components/r-grid/r-grid.story.js
- packages/recomponents/src/components/r-grid/r-grid.vue
We should have an opportunity to highlight some cells.
> feat(r-grid): highlight cell in the grid by condition

- packages/recomponents/src/components/r-month-picker/__snapshots__/r-month-picker.spec.js.snap
- packages/recomponents/src/components/r-month-picker/month-picker-mixin.js
- packages/recomponents/src/components/r-month-picker/r-month-picker-input.spec.js
- packages/recomponents/src/components/r-month-picker/r-month-picker-input.story.js
- packages/recomponents/src/components/r-month-picker/r-month-picker-input.vue
There was set `bottomEnd` position for month picker.
> fix(r-month-picker): fixing position issue and unit tests

- packages/recomponents/src/components/r-date-input/r-date-input.vue
- packages/recomponents/src/components/r-date-range/__snapshots__/r-date-range.spec.js.snap
- packages/recomponents/src/components/r-date-range/r-date-range.scss
- packages/recomponents/src/components/r-date-range/r-date-range.vue
- packages/recomponents/src/components/r-month-picker/__snapshots__/r-month-picker-input.spec.js.snap
- packages/recomponents/src/components/r-month-picker/__snapshots__/r-month-picker.spec.js.snap
- packages/recomponents/src/components/r-month-picker/r-month-picker-input.spec.js
On mobile devices, it was a problem to pick the date in the double calendar.
Check the window width and if it is a mobile device - show only 1 calendar, do not show preset.
> Fix mobile view of calendar and date range picker

- packages/recomponents/src/components/r-date-range/r-date-range.spec.js
> fix(r-date-range): Add unit test for r-date-range component

- packages/recomponents/src/components/r-month-picker/__snapshots__/r-month-picker.spec.js.snap
- packages/recomponents/src/components/r-month-picker/r-month-picker.spec.js
- packages/recomponents/src/components/r-month-picker/r-month-picker.vue
> Add small unit test for month picker

- packages/recomponents/src/components/r-tabs/r-tab.vue
- packages/recomponents/src/components/r-tabs/r-tabs.vue
The functionality to allow to hide the buttons is needed.
> fix(r-tabs): Allow to hide tab buttons

- packages/recomponents/src/components/r-button/r-button.scss
- packages/recomponents/src/components/r-button/r-button.story.js
- packages/recomponents/src/components/r-button/r-button.vue
- packages/recomponents/src/styles/theme.scss
- yarn.lock
We have button types: `default`, `danger`, `link` and `primary`. There is a `positive` (green) button type added.
> Add positive button type

- packages/recomponents/src/common/helpers/format-date.js
- packages/recomponents/src/components/r-date-input/__snapshots__/r-date-input.spec.js.snap
- packages/recomponents/src/components/r-date-input/calendar-presets.js
- packages/recomponents/src/components/r-date-input/r-calendar-manager.vue
- packages/recomponents/src/components/r-date-input/r-date-input.story.js
- packages/recomponents/src/components/r-date-input/r-date-input.vue
- packages/recomponents/src/components/r-date-input/r-date-range-button-group.spec.js
- packages/recomponents/src/components/r-date-input/r-date-range-button-group.vue
Upgrading the `v-calendar` I removed timezone handling, but implementing the new version to the projects I found that it would be much more convenient to have it here.
> Handle user's timezone

- packages/recomponents/src/components/r-date-input/r-calendar-manager.vue
- packages/recomponents/src/components/r-date-input/r-date-input.vue
There was a request to set `00:00` for start date and `23:59` for end as default values
> Set 12:00 AM and 11:59 PM time picker by default

- packages/recomponents/src/common/datetime-formats.js
- packages/recomponents/src/components/r-date-input/r-calendar-manager.vue
- packages/recomponents/src/components/r-date-input/r-date-input.story.js
- packages/recomponents/src/components/r-date-input/r-date-input.vue
- packages/recomponents/src/components/r-date-input/r-date-range-button-group.vue
Support 24-hr time format for date-time picker
> 24h time picker

- packages/recomponents/src/components/r-date-input/r-calendar-manager.vue
- packages/recomponents/src/components/r-date-input/r-date-input.scss
- packages/recomponents/src/components/r-date-input/r-date-input.vue
There was no fallback placement set for calendar popover:
Added a fallback placement of the popover
> Placement calendar fix

- package.json
- yarn.lock
Security alerts
Added resolutions
> fix(dependencies): add resolutions for several packages

- packages/recomponents/src/styles/recomm.scss
Update the `@font-face` styles to include the `font-display: swap;` for optimization.
By using `font-display: swap;`
> perf(fonts): Add font display swap property
