Rebilly/rebilly-recomponents

- packages/nuxt/package.json
Remove recomponents from nuxt demo to pass first release via CI
> fix(tools): Remove temporary recomponents from nuxt demo

- packages/recomponents/README.md
- packages/recomponents/src/components/r-badge/r-badge.md
- packages/recomponents/src/components/r-badge/r-badge.vue
- packages/recomponents/src/components/r-button/r-button.md
- packages/recomponents/src/components/r-button/r-button.vue
- packages/recomponents/src/components/r-checkbox/r-checkbox.md
- packages/recomponents/src/components/r-checkbox/r-checkbox.vue
- packages/recomponents/src/components/r-dropdown/r-dropdown.md
- packages/recomponents/src/components/r-dropdown/r-dropdown.vue
- packages/recomponents/src/components/r-icon-button/r-icon-button.md
- packages/recomponents/src/components/r-icon-button/r-icon-button.vue
- packages/recomponents/src/components/r-icon/r-icon.md
- packages/recomponents/src/components/r-icon/r-icon.vue
- packages/recomponents/src/components/r-img/r-img.vue
- packages/recomponents/src/components/r-input/r-input.md
- packages/recomponents/src/components/r-input/r-input.vue
- packages/recomponents/src/components/r-loader/__snapshots__/r-loader.spec.js.snap
- packages/recomponents/src/components/r-loader/r-loader.md
- packages/recomponents/src/components/r-loader/r-loader.scss
- packages/recomponents/src/components/r-loader/r-loader.spec.js
- packages/recomponents/src/components/r-loader/r-loader.vue
- packages/recomponents/src/components/r-radio/r-radio.vue
- packages/recomponents/src/components/r-tile/__snapshots__/r-tile.spec.js.snap
- packages/recomponents/src/components/r-tile/r-tile.md
- packages/recomponents/src/components/r-tile/r-tile.spec.js
- packages/recomponents/src/components/r-tile/r-tile.vue
- packages/recomponents/src/index.js
- packages/recomponents/src/stories/payment-form.story.js
Lack of styles in umd module version of recomponent + lack of examples for it
Add entire stylesheet to the page won't help because all content of component it hidden by shadow dom, only styles in SFC will be used. Import of external scss file helps to solve that issue, and that styles will be extracted to separate css file anyway
> Before release

- packages/recomponents/src/styles/theme.scss
The color of danger button should be the same with re-ui
~Actually I'm confused why the style is not as the same with re-ui, so I just copied 1 line of the CSS to here. the color is the same but I don't find a var name equals `#ff201b`, how to name it, I still don't know, need your help here @cesarlevel : the most difficult stuff in programming, how to name a var :-)~
Ah fixed it, anyway, have a review.
None
> fix(button): Adjust the color, the same with re-ui

- packages/recomponents/src/components/r-badge/__snapshots__/r-badge.spec.js.snap
- packages/recomponents/src/components/r-badge/r-badge.md
- packages/recomponents/src/components/r-badge/r-badge.scss
- packages/recomponents/src/components/r-badge/r-badge.spec.js
- packages/recomponents/src/components/r-badge/r-badge.story.js
- packages/recomponents/src/components/r-badge/r-badge.vue
- packages/recomponents/src/styles/theme.scss
- RBadge had a slot for text that was really unnecessary. To setup the component and put some text you would need to define the slot:
`<r-badge><span slot="text">Some text<span></r-badge>`
now we can just do `<r-badge>Some text</r-badge>`
- Eliminated the `actions` and `text` slot. 
- Added a new prop call `close` to add a close icon
- Updated the UI for the component
- Changed the CSS to use SMACSS
- Updated tests
> Fix badge component

- packages/recomponents/src/components/r-input/r-input.md
- packages/recomponents/src/components/r-input/r-input.scss
- packages/recomponents/src/components/r-input/r-input.story.js
- packages/recomponents/src/components/r-input/r-input.vue
v-input is updated in recomm, so I have to update r-input in order to keep the same
v-input is used in the global search component in recomm, so I need to update r-input.
> fix(r-input): update r-input as it's updated in recomm again

- packages/recomponents/src/components/r-badge/r-badge.scss
- packages/recomponents/src/components/r-badge/r-badge.spec.js
- packages/recomponents/src/components/r-badge/r-badge.vue
The default value for the prop `type` wasn't kicking in when passing a falsy value to the prop
Check if there is a falsy value and if there is it will return `default`
> fix(RBadge): Add default class to RBadge

- packages/recomponents/src/components/r-tabs/r-tabs.vue
RTabs would not work in Recomm because it did not include the `value` field in `tab-selected` event's payload
This PR add `value` in `tab-selected` event's payload
- N/A [ ] Readme file updated with actual description and example
- N/A [ ] Added all ARIA attributes required for component
- N/A [ ] Added tests for both browser and SSR render and for all components properties
- N/A [ ] Added story with all knobs and actions
Jira Task: [GWY-13960](https://jira.ilabsinc.com/browse/GWY-13960)
> fix(rtabs): include the value field in the payload of 'tab-select'

- packages/recomponents/src/components/r-checkbox/r-checkbox.vue
Updated method name that's supposed to be used only internally. Surely not fond of the name, but at least it's clear what it does.
Also added a few comments, that I'll later elaborate on in the PR's comments.
Misleading method name. Missing information how the component actually works (not that straightforward to follow).
Provides a basic set of comments, as well as straightforward method name.
> Updating RCheckbox method name and adding comments

- packages/recomponents/.storybook/webpack.config.js
- packages/recomponents/vue.config.js
Unable to use '@' alias for styles
Updates both webpack and storybook config and now we can do next:
> Add alias for SASS

- packages/recomponents/src/components/r-icon/r-icon.vue
Cannot render any component with icons in IE11
Changed code to use IE 11 DOM method
Component looks unstyled till we will add CSS Vars polyfill, we will do that later.
> fix(component): Fix icons in IE 11

- packages/recomponents/package.json
- packages/recomponents/src/components/r-radio/r-radio.spec.js
Subcommands in a few `package.json` scripts are being run in two separate processes (first one in a background process and the second one in a standard process)
Subcommands are now being run sequentially
> Fix package.json to run script subcommands sequentially

- packages/recomponents/src/components/r-tabs/__snapshots__/r-tabs.spec.js.snap
- packages/recomponents/src/components/r-tabs/id-helpers.js
- packages/recomponents/src/components/r-tabs/r-tab.vue
- packages/recomponents/src/components/r-tabs/r-tabs.scss
- packages/recomponents/src/components/r-tabs/r-tabs.spec.js
- packages/recomponents/src/components/r-tabs/r-tabs.story.js
- packages/recomponents/src/components/r-tabs/r-tabs.vue
- packages/recomponents/src/styles/mixins.scss
- Tabs had no focus states
- Were not operable via keyboard
- Did not comply with ARIA standards for accessibility
Tabs should now be accessible out of the box without additional input from the developer.
> Make tabs accessible by default

- packages/recomponents/src/components/r-input/r-input.vue
Fix undefined exception, see screenshot.
RInput itself doesn't have this bug, but if another component extends it. eg `v-inline-input.vue`, as the view is not rendered, so undefined exception. adding `if` fixed this small bug.
> fix(RInput): Fix undefined exception

- packages/recomponents/src/components/r-select/r-select.scss
r-select tag badges close icon should be aligned in the middle.
> fix(r-select): Align close icon in r-select tag badges

- packages/recomponents/jest.config.js
- packages/recomponents/src/components/index.js
- packages/recomponents/src/components/r-select/r-select.spec.js
- packages/recomponents/src/directives/index.js
- packages/recomponents/src/directives/r-click-outside/r-click-outside.spec.js
- packages/recomponents/src/directives/r-content/r-content.spec.js
- packages/recomponents/src/directives/r-tooltip/r-tooltip.spec.js
- packages/recomponents/src/index.js
- packages/recomponents/src/setup-test.js
Our components use directives, but manually importing and registering directives for each test file is cumbersome and error prone. 
This PR adds a setup file which registers all directives to the global Vue object before tests run. This is *technically* not the cleanest way to run tests, but it is very low-risk and, in my opinion, easier to maintain.
I'm open to feedback if the team thinks this approach is not appropriate!
> Add global test setup and register directives globally

- packages/recomponents/.eslintrc
- packages/recomponents/src/components/r-select/r-select.vue
disallow use of v-html to prevent XSS attack
1. add rule `vue/no-v-html` in eslint
2. remove `v-html` in r-select
> fix(RSelect): disallow use of v-html to prevent XSS attack

- packages/recomponents/src/components/r-select/r-select.vue
`r-select` toggles when remove icon is clicked.
> fix(r-select): Do not toggle r-select when tag is removing

- packages/recomponents/src/styles/recomm.scss
Leading is wrong on H1
Fix error when moving from PX to REM => `-0.6px` should be `-0.06rem`
> Fixed H1 Leading

- packages/recomponents/src/components/r-popper/r-popper.scss
- packages/recomponents/src/components/r-popper/r-popper.vue
I updated the transition feature for the RPopper, no bugs in storybook, but it causes bugs in Recomm. Luckily is that we still didn't use the latest version, so NO real bugs happened in Recomm :-) 
- fixed the error on the console: `this.contentEL.childNodes[0].getBoundingClientRect is not a function`
- fixed the position issue.
- maked the content of RPopper visible
Sometimes the demo is OK in storybook, it doesn't always mean it's OK in Recomm as Recomm is more complex, the demo doesn't cover all the cases. so still need to have a test in Recomm if required.
> fix(RPopper): fix the transition bug

- packages/recomponents/src/components/r-modal/r-modal.vue
`appear` event is triggered even the RModal is hidden, so add `r-no-scroll` to the body and cause the whole page can't be scrollable, which is bad.
Just removed `appear` event as I noticed this event is never used in Recomm, and fixed the scroll bug.
> fix(RModal): delete appear event

- packages/recomponents/src/components/r-popper/r-popper.story.js
The disabled state wouldn't work in the `RPopper` demo.
> chore(r-popper): fix disabled state in storybook demo

- packages/recomponents/src/components/r-popper/r-popper.scss
- packages/recomponents/src/styles/animate.scss
Opacity was not active during animation
Disable ability to override opacity for element in <transition> component
* https://vuejs.org/v2/guide/transitions.html#Transition-Classes
> Fix popper animation

- packages/recomponents/README.md
- packages/recomponents/package.json
We forgot to add -s option when building storybook so the static was not found giving 404 errors in the deployed version of storybook
Adding `-s ./public` to `build-storybook` script in` package.json` so that static contents are copied when building. 
- [ x] Readme file updated with actual description and example
> add static directory option to storybook build script (GWY-13645)

- packages/recomponents/src/components/r-badge/r-badge.spec.js
- packages/recomponents/src/components/r-badge/r-badge.vue
r-badge did not emit a click event
this PR adds a click event when clicking on a badge, and properly stops propagation of the click on the close icon if present.
> Add click event to r-badge

- packages/recomponents/src/components/r-badge/r-badge.spec.js
The RBadge test descriptors were a bit confusing, and the suite was missing one test.
Updates the descriptions for each test, and adds a test case for clicking on the `close` button to ensure it does not emit a `click` event in that case (only a `close` event)
> fix(RBadge): improve RBadge tests and test descriptors

- packages/recomponents/.storybook/webpack.config.js
- packages/recomponents/src/components/r-checkbox/r-checkbox.scss
- packages/recomponents/src/components/r-input/r-input.scss
- packages/recomponents/src/styles/theme.scss
Checkbox styles was inconsistent
* Removes duplicated css variables usage
* Removes 2-level inheritance in variables
Right now `r-field-label` and `r-field-label-toggle` can be used together because toggle override most of properties of default label - no need to update markup.
> fix(component): Cleanup RCheckbox styles

- packages/recomponents/src/components/r-toast/r-toast.scss
RToast was rendering strangely in Recomm, with a scrollbar appearing on the container. 
This PR removes styles on the `r-toast-container` CSS class which did not match the original implementation from Recomm and which were causing the bug.
> fix(RToast): Fix visual scroll bug

- packages/recomponents/src/common/helpers/default-error-handler.js
- packages/recomponents/src/components/r-toast/r-toast.spec.js
- packages/recomponents/src/index.js
- packages/recomponents/src/plugins/r-toast-manager/r-toast-manager.js
Adding new `fromError()` method on `r-toast-manager.js`.
This method has the option to either use the `DefaultErrorHandler` or a custom error handler passed via the plugin options of Recomponents.
> Add new method on rtoast

- packages/recomponents/src/directives/r-tooltip/r-tooltip.js
- packages/recomponents/src/directives/r-tooltip/r-tooltip.story.js
Tooltip layout is incorrect for elements with full-page width:
Update of isOut.right calculation is enough.
> fix(directive): Fix position of tooltip for block elements

- packages/recomponents/src/components/r-toast/r-toast.spec.js
- packages/recomponents/src/index.js
- packages/recomponents/src/plugins/r-toast-manager/index.js
- packages/recomponents/src/plugins/r-toast-manager/r-toast-manager.js
* Expose `RToastManager` for use outside the `Recomponents` plugin
* Improve naming
> chore(r-toast): expose RToastManager and improve naming

- packages/recomponents/src/components/r-toast/__snapshots__/r-toast.spec.js.snap
- packages/recomponents/src/components/r-toast/r-toast.story.js
- packages/recomponents/src/components/r-toast/r-toast.vue
* We removed all entries of v-html in Recomponents because of security reason, but we need the way to style toast messages.
* Added support of render function as RToast child content
> feat(component): Add render function support for RToast

- packages/recomponents/package.json
- packages/recomponents/src/components/r-input/r-input.story.js
- packages/recomponents/src/components/r-select/r-select.story.js
- packages/recomponents/yarn.lock
In https://github.com/Rebilly/rebilly-recomponents/pull/145/ proposed to create separate prop for tag validator in RSelect component. I'd like to propose use only Vuelidate outside of select component.
Added two stories how to use Vuelidate with Recomponents
> chore(storybook): Add 2 stories for Vuelidate

- packages/recomponents/src/components/r-pagination/r-pagination.story.js
- packages/recomponents/src/components/r-pagination/r-pagination.vue
* We had unexpected list provider call when the computed property was changed
* AJAX request in computed property calculation is a bad approach, remove it is enough to fix this issue.
> fix(r-pagination): Double requests on pagination init

- packages/recomponents/.storybook/knobs.js
- packages/recomponents/src/components/r-input/r-input.story.js
- packages/recomponents/src/components/r-select/r-select.story.js
* Go to https://recomponents.rebilly.com/?path=/story/components-select--component
* Observer error `this.validate.$touch is not a function`
* Created shared knob for all components that require validation in stories
> chore(storybook): Create shared validation mock for knobs

- packages/recomponents/src/components/r-pagination-control/r-pagination-control.vue
- packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination.spec.js.snap
- packages/recomponents/src/components/r-pagination/r-pagination.spec.js
- packages/recomponents/src/components/r-pagination/r-pagination.vue
There is a knobb with visible page navigation buttons, it doesn't work properly. 
How it was: [video](https://jira.ilabsinc.com/secure/attachment/19384/19384_Screen+Recording+2020-01-23+at+04.21.39.mov)
Now:
> fix(r-pagination): wrong quantity of visible buttons

- packages/recomponents/src/components/r-popper/r-popper.scss
- packages/recomponents/src/components/r-popper/r-popper.story.js
Small change for fixing the view of r-popper when there are more than 16 options (one line options)
> fix(r-popper): fix view of more than 16 options in popper menu

- packages/recomponents/src/styles/theme.scss
The style of .r-tab-content is not the same with .tab-content so the UI is not that right
Before
After
> fix(r-tabs): update the style

- packages/recomponents/src/components/r-button-group/r-button-group.scss
Gap between RButtonGroup buttons only in Safari.
Additional negative margin did the trick, was not related to font-size or letter spacing.
> fix(component): Fix RButtonGroup items in Safari

- packages/recomponents/src/components/r-date-range/r-date-range.story.js
- packages/recomponents/src/components/r-date-range/r-date-range.vue
- packages/recomponents/src/components/r-grid/r-grid.md
- packages/recomponents/src/components/r-grid/r-grid.story.js
- packages/recomponents/src/components/r-grid/r-grid.vue
- packages/recomponents/src/components/r-repeater/r-repeater.md
- packages/recomponents/src/components/r-repeater/r-repeater.vue
`RGrid` has a fullscreen loader by default - that's not the common case. Added the property to be able to define it. And fixed the story.
`RDateRange` is not supporting the period as an object.
> fix(r-date-range): small changes and fixies for report integration

- packages/recomponents/src/components/r-grid/columnTypes/numeric.js
- packages/recomponents/src/components/r-grid/r-grid.story.js
The grid with the type `numeric` should support international formatting
> feat(r-grid): support international format for numeric grid type

- packages/recomponents/src/components/r-input/r-input.vue
- packages/recomponents/src/components/r-select/r-select.vue
A label for a form control helps everyone better understand its purpose. When using labels we need to bind the `for` attribute to the internal form control.
- Adds label for attribute pointing to the related internal input in all the possible variants of `<r-input>` component 
- Adds label for attribute pointing to the related internal input in all the possible variants of `<r-select>` component
> chore(component): add for attribute to labels in r-input and r-select

- packages/recomponents/src/index.js
RToast components are not closable in Recomm. RToast support ability to close by it self, but we cannot enable this feature during `Vue.use(Recomponents)` installation.
* Pass option to RToastManager from global options
> Pass close option to RToastManager

- packages/recomponents/README.md
- packages/recomponents/src/components/r-toast/r-toast.md
- packages/recomponents/src/components/r-toast/r-toast.story.js
- packages/recomponents/src/index.js
* Name of option for toasts was to generic
* Not clear how to override closable / non-closable behaviour
* Documentation update with examples
* Option rename
> Update closable / non-closable RToasts

- packages/recomponents/src/components/r-modal/r-modal.md
- packages/recomponents/src/components/r-modal/r-modal.vue
We want to add an action to the modal header, as in this RFC:
https://product.rebilly.dev/priorities/kyc/0000-kyc-workbench-ux/#basic-example
This PR adds a new slot to the left of the close button
> feat(header-actions): Add header actions slot to r-modal

- packages/recomponents/src/components/r-modal/r-modal.scss
Header modal title shouldn't override the title original string.
Removed CSS `text-transform: capitalize` rule.
> fix(modal-title): Fix text transform

- packages/recomponents/src/components/r-grid/r-grid.scss
Forgot to set the width of `r-grid`.
There was set only the `min-width`.
> Hot fix for width of r-grid with frozen column

- packages/recomponents/src/components/r-button/__snapshots__/r-button.spec.js.snap
- packages/recomponents/src/components/r-button/r-button.vue
- packages/recomponents/src/components/r-date-range/__snapshots__/r-date-range.spec.js.snap
- packages/recomponents/src/components/r-icon-button/__snapshots__/r-icon-button.spec.js.snap
- packages/recomponents/src/components/r-icon-button/r-icon-button.vue
- packages/recomponents/src/components/r-pagination-control/__snapshots__/r-pagination-control.spec.js.snap
- packages/recomponents/src/components/r-pagination/__snapshots__/r-pagination.spec.js.snap
- packages/recomponents/src/components/r-webcomponent/__snapshots__/r-webcomponent.spec.js.snap
Buttons containing a `<div> slot` (used to add capitalize class) were not accesible (Empty [accesible name](https://www.w3.org/TR/accname-1.1/)).
Adding a[ button role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role) makes the button accesible. 
This also allows these buttons to be more testable by tools like testing library that uses [role to query UI elements](https://testing-library.com/docs/dom-testing-library/api-queries#byrole).
> Make buttons with capitalized text accesible

- packages/recomponents/src/components/r-grid/columnTypes/date.js
For date column, it shows UTC formatted date, should show local time.
> fix(r-grid): fix date column timezone issue

- packages/recomponents/src/components/r-grid/r-grid.scss
Numeric type columns are formatted by default (with special readable font and right-aligned).
> fix(r-grid): make numeric columns formatted and hide scrollbars

- packages/recomponents/src/components/r-input/r-input.vue
The custom attributes passed to `r-input` were duplicated between `parent div` and `child input`
Setting [inheritAttrs](https://vuejs.org/v2/api/#inheritAttrs) to false avoids the root div to have duplicated attrs.
> Add inheritAttrs:false to avoid attrs passed to inner input being duplicated in parent div (inside r-input)

- packages/recomponents/src/components/r-grid/columnTypes/numeric.js
- packages/recomponents/src/components/r-grid/r-grid.story.js
There should be supported duration type columns.
> fix(r-grid): support duration columns for r-grid

- packages/recomponents/src/components/r-date-range/r-date-range.vue
Keep the periods as a string (now there are strings for manual selection and moment for presets).
When loads if the selected period is relative it doesn't work properly.
> fix(r-date-range): Fix relative periods and emit the periods as a string

- packages/recomponents/src/components/r-date-range/r-date-range.vue
If there are set the minDate or maxDate, past / future hours are not allowed to be selected.
> fix(r-date-range): restrict the time selection with min and max dates

- packages/recomponents/src/components/r-date-range/r-date-range.spec.js
- packages/recomponents/src/components/r-date-range/r-date-range.vue
- packages/recomponents/src/components/r-month-picker/__snapshots__/r-month-picker-input.spec.js.snap
- packages/recomponents/src/components/r-month-picker/__snapshots__/r-month-picker.spec.js.snap
- packages/recomponents/src/components/r-month-picker/month-picker-mixin.js
- packages/recomponents/src/components/r-month-picker/r-month-picker-input.spec.js
- packages/recomponents/src/components/r-month-picker/r-month-picker.spec.js
The date range is processed twice, resulting in confusion with timezones.
The date range picker returns the ready values of `start` and `end` in the timezone which was selected in the parent application.
> Fix relative periods for r-range-picker

- packages/recomponents/src/components/r-select/r-select.spec.js
- packages/recomponents/src/components/r-select/r-select.story.js
- packages/recomponents/src/components/r-select/r-select.vue
`r-select` didn't call the provided `asyncFind` method.
Call `asyncFind` on `search` watcher.
> fix(r-select): fix calling asyncFind on search

- packages/recomponents/src/components/r-select/r-select.spec.js
- packages/recomponents/src/components/r-select/r-select.vue
Setting the `autocomplete` attribute of the input to `off` doesn't work on Chrome, making it show the autocomplete dropdown.
By adding autocomplete as a prop we can pass any value to it, e.g. 'none' and avoid the dropdown to be shown
> fix(r-select): Update autocomplete attribute

- packages/recomponents/src/components/r-date-input/r-date-input.vue
It picks the current date with the current time, we should pick the start of the day for single date type of the `r-date-input` picker.
> Pick the start of the day for single date type input

- packages/recomponents/src/components/r-date-input/r-calendar-manager.vue
Previous version of the `r-date-input` was created with a `bottom` placement approach.
Now the fallback position sometimes uses `top` placement which is not supported by the projects where it is used.
Set the `bottom` placement as a default and as a only allowed and fallback placements.
> Set placement of the calendar popover to always bottom

- packages/recomponents/src/components/r-date-input/r-date-input.vue
When the user picks a simple date (no range and time), it was converting the date not correctly.
> fix(r-date-input): timezone for simple date

- packages/recomponents/package.json
- yarn.lock
Upgrading `@sematic-release` dependencies: 
- "@semantic-release/changelog": "^3.0.4" => "5.0.1"
- "@semantic-release/commit-analyzer": "^6.3.0" => "8.0.1"
- "@semantic-release/git": "^7.0.16" => "9.0.0"
- "@semantic-release/github": "^5.4.2" => "7.2.3"
- "@semantic-release/npm": "^5.1.13" => "7.1.3"
- "@semantic-release/release-notes-generator": "^7.3.0" => "9.0.3"
> chore(deps): bump @semantic-release dependencies

- packages/recomponents/src/components/r-select/r-select.vue
Steps to reproduce: 
1. Use an `r-select` component with async search and enough options for several pages 
2. Use the search and select the value from not the first page
Expected behaviour: input shows the selected value
Actual behaviour: in a couple of seconds the value disappears.
Keeping the object of selected value
> fix(r-select): keep the object value for selected

- .github/workflows/recomponents.yml
`Semantic release` on the GHA [failed](https://github.com/Rebilly/rebilly-recomponents/runs/3528783924?check_suite_focus=true) 
Replace master with main
> fix(r-select): replace master with main

- packages/recomponents/package.json
- packages/recomponents/src/components/r-checkbox/r-checkbox.vue
- packages/recomponents/src/components/r-date-input/r-date-input.vue
- packages/recomponents/src/components/r-input/r-input.vue
- packages/recomponents/src/components/r-popper/r-popper.vue
- packages/recomponents/src/components/r-radio/r-radio.vue
- packages/recomponents/src/components/r-select/r-select.vue
- packages/recomponents/src/components/r-tabs/r-tab.vue
- packages/recomponents/src/components/r-tabs/r-tabs.spec.js
- packages/recomponents/src/components/r-toggle/r-toggle.vue
- yarn.lock
Shortid is deprecated and is a security threat. Replace it with Nanoid.
fix #272
The shortid package is now deprecated.
Replace shortid with nanoid.
> fix: migrate from shortid to nanoid

- packages/recomponents/src/components/r-date-input/r-calendar-manager.vue
- packages/recomponents/src/components/r-date-input/r-date-input.vue
For `type` of Date Input it should `@input` with the date only, without any time and timezone markers.
Now it looks like `@input('2022-01-01')`
> fix(r-date-input): fix the input event prop for date only type

- packages/recomponents/src/components/r-avatar/r-avatar.scss
Issue #315 
Checked the usages of `r-avatar` component. 
Removed the extra space for `.r-avatar-main` class
> fix(r-avatar): remove extra margin for .r-avatar-main

- packages/recomponents/src/components/r-pagination/r-pagination.vue
- packages/recomponents/src/index.js
Our plan to migrate workbench and recomm to vue3 involves using `@vue/app` compat mode with `recomponents` original + `recomponents-next`. 
We need some adjustments for tests to be working in that mode.
> fix: vue 3 app compat
